"""Phase 20.3: scoped, deterministic mutation-testing harness.

WHAT THIS DOES. Generates syntactic mutants of the claim-bearing surface defined in
docs/verification/surface.md (hardcoded below rather than parsed from that document,
per the task brief; the line ranges are cited from that document, not guessed), runs
each mutant's targeted test subset, confirms every survivor against the full suite,
and writes docs/verification/mutation_report.md.

SAFETY. This script NEVER writes to the real src/ or scripts/ tree. Every mutation is
applied to a throwaway copy of the repository under a scratch directory outside the
repo (see SCRATCH_ROOT below); the real tree is read from once, to seed that copy, and
otherwise only ever hashed. A sha256 manifest of every file under the real src/ and
scripts/ is taken at startup and again at exit; the two must match exactly or the
script aborts loudly (see verify_manifest_or_abort). This is the reason mutations are
implemented as an in-memory text splice applied to, and then always restored from, a
byte-for-byte copy held in the scratch tree, never as an edit to a path under REPO_ROOT.

DETERMINISM. Mutation candidates are generated by walking each target file's ast once,
producing one MutationCandidate per applicable (node, mutation kind) pair, then sorted
by (file, line, col, kind, detail). If a file's candidate pool exceeds its budget quota,
the quota is drawn with random.Random(seed).sample() (seed fixed by --seed, default
DEFAULT_SEED below) applied to that already-sorted pool, then the sample is re-sorted
into the same fixed order before being run. Two runs at the same --budget and --seed
therefore generate and report on an identical mutant set in an identical order; the
only thing that legitimately differs between two runs is wall-clock runtime, which is
why the report keeps that number on its own line rather than folding it into anything
that is asserted to be reproducible.

USAGE.
    python scripts/mutation_check.py                       # budget 200, default seed
    python scripts/mutation_check.py --budget 12 --report X # small run, custom report path
    python scripts/mutation_check.py --files capacity metrics
"""

from __future__ import annotations

import argparse
import ast
import bisect
import dataclasses
import hashlib
import json
import random
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Outside the repo entirely, per the phase brief. tempfile.gettempdir() resolves to
# C:\Users\<user>\AppData\Local\Temp on this machine, so the scratch tree lands under
# the system temp directory without hardcoding a username. Always wiped and recopied
# at the start of a run (prepare_scratch_tree), so nothing from a previous run's
# mutated state can leak into the next.
SCRATCH_ROOT = Path(tempfile.gettempdir()) / "microgrid_mutation_scratch" / "tree"

# The thesis's own student ID (see docs/PROJECT_CONTEXT.md): fixed, memorable,
# documented. Used only to seed the deterministic down-sampling in allocate_budget's
# companion selection step below; never used for anything that should vary run to run.
DEFAULT_SEED = 26170

EXCLUDE_DIR_NAMES = {".git", "docs", ".pytest_cache", "__pycache__"}


# ---------------------------------------------------------------------------
# The claim-bearing surface (docs/verification/surface.md), hardcoded and cited.
# ---------------------------------------------------------------------------
#
# capacity.py and metrics.py: "whole file" per surface.md sections 1 and 2.
# model.py: step() is surface.md section 4, "model.py:246-298"; the per-broker
#   contribution computation it cites (model.py:279-281) is inside that range.
# consumer.py: surface.md section 3, "consumer.py:90-146"
#   (_current_capacity_surcharge + _apply_demand_deferral, the whole D7 path).
# analyze_sweep.py: surface.md section 5a, the eight named "small stats helpers"
#   (analyze_sweep.py:245-430, section headers "Small stats helpers" and
#   "Multiple-comparison correction"). Section 5b (the CSV-assembly functions'
#   embedded arithmetic: build_summary_stats's mean/std/CI at 506-521, the six
#   reindex call sites, the pnl-leak tolerance calc, build_monopoly_comparison's
#   n_improved count) is DELIBERATELY EXCLUDED from this harness's target ranges:
#   every one of those spans already has a dedicated, hand-built regression test
#   added by the surface.md revision (see that document's triage table), each of
#   which was hand-verified against a specific mutation at the time it was
#   written; asking this harness's generic catalog to rediscover the same 13
#   already-confirmed hazards, plus the one already-documented deferred gap
#   (line 640), would spend a large share of this item's 200-mutant budget
#   re-proving work the previous item already did and documented. Section 5a
#   (below) is genuinely this item's to cover: those eight functions had no
#   line-level mutation evidence before this item. This is a scoping decision,
#   not an oversight; it is restated in the report's "Surface and allocation"
#   section.
TARGETS: dict[str, list[tuple[int, int]]] = {
    "src/microgrid_sim/environment/capacity.py": [(1, 10**6)],
    "src/microgrid_sim/environment/metrics.py": [(1, 10**6)],
    "src/microgrid_sim/environment/model.py": [(246, 298)],
    "src/microgrid_sim/agents/consumer.py": [(90, 146)],
    "scripts/analyze_sweep.py": [
        (245, 251),  # t_ci_halfwidth
        (254, 265),  # cohens_d_independent
        (268, 294),  # paired_comparison
        (297, 311),  # paired_pct_change
        (325, 346),  # holm_bonferroni
        (349, 370),  # benjamini_hochberg
        (373, 396),  # bootstrap_paired_diff_ci
        (399, 430),  # _ci_disagreement
    ],
}

# Which test modules to run for a fast per-mutant kill/survive check on each target
# file. Derived by reading each candidate test file's imports (not guessed): every
# module below imports the corresponding source module directly, or (for
# analyze_sweep.py, which is a script, not a package) loads it via
# importlib.util.spec_from_file_location, which tests/test_multiple_comparison_correction.py
# does for exactly the section-5a functions in scope here.
#
# tests/test_golden_master.py is DELIBERATELY EXCLUDED from every targeted subset
# below. It touches capacity.py, metrics.py, model.py and consumer.py all at once
# (it pins whole-run output), so putting it in every targeted subset would make the
# fast per-mutant loop pay its ~16s cost (measured serially; see report) on every
# single one of this item's 200 mutants, most of which get killed by a much cheaper,
# more targeted test anyway. Instead, every mutant that survives its targeted subset
# is re-run against the FULL suite (which includes test_golden_master.py) before
# being reported as a survivor (see the survivor-confirmation loop in main()), so nothing
# golden-master-only would have caught can slip through unconfirmed; the cost of this
# decision is that golden master's ~16s is paid once per SURVIVOR at confirmation
# time, not once per mutant in the fast loop. See the report's
# "golden_master_in_targeted_subsets" line for the measured survivor count this cost
# a comment on.
TARGETED_TESTS: dict[str, list[str]] = {
    "src/microgrid_sim/environment/capacity.py": [
        "tests/test_capacity.py",
        "tests/test_surcharge_mode.py",
        "tests/test_surcharge_divisor.py",
    ],
    "src/microgrid_sim/environment/metrics.py": ["tests/test_metrics.py"],
    "src/microgrid_sim/environment/model.py": ["tests/test_model.py", "tests/test_integration.py"],
    "src/microgrid_sim/agents/consumer.py": ["tests/test_agents.py"],
    "scripts/analyze_sweep.py": ["tests/test_multiple_comparison_correction.py"],
}

# At budget 200: weight toward capacity.py and metrics.py, the two files surface.md
# calls "nothing left to triage" / "0 missed" i.e. already fully covered by line
# count, which makes them the highest-value place to spend a mutation budget (line
# coverage says every line RUNS; it says nothing about whether the arithmetic on
# that line is right, which is exactly what a surviving mutant would expose). Sums
# to 200; allocate_budget() rescales this proportionally for any other --budget.
WEIGHTS: dict[str, int] = {
    "src/microgrid_sim/environment/capacity.py": 70,
    "src/microgrid_sim/environment/metrics.py": 60,
    "src/microgrid_sim/environment/model.py": 30,
    "src/microgrid_sim/agents/consumer.py": 20,
    "scripts/analyze_sweep.py": 20,
}

CATALOG = [
    ("arith_op_swap", "arithmetic operator swaps (+ - * / // %)"),
    ("cmp_op_swap", "comparison operator swaps (< <= > >= == !=)"),
    ("boundary_shift", "boundary shift: an int literal used as an index/count/divisor, to x-1 and x+1"),
    ("bool_gate", "boolean gate replacement: an if/while condition replaced by True, and by False"),
    ("bound_removal", "clip/max/min bound removal: drop a max(...)/min(...)/np.clip(...) wrapper, keep one operand"),
    ("sign_flip", "sign flip on a clipped/bounded quantity: negate the whole max/min/clip expression"),
    ("identifier_swap", "swap two same-typed identifiers (bare names) appearing in the same expression"),
]

TARGETED_TIMEOUT_S = 180
FULL_SUITE_TIMEOUT_S = 300
FULL_SUITE_ARGS = ["-q", "--no-header", "-x", "-n", "16"]


# ---------------------------------------------------------------------------
# Source-span bookkeeping: exact text splices driven by ast col/lineno offsets.
# ---------------------------------------------------------------------------


class SourceMap:
    """Maps ast (lineno, col_offset) pairs, 1-indexed lines, to absolute character
    offsets into a source string with '\\n' line endings (i.e. the same string that
    was passed to ast.parse), and back. This is what lets a mutation be a splice of
    exact character ranges rather than a whole-file ast.unparse, so everything
    outside the mutated span stays byte-identical to the original."""

    def __init__(self, text: str):
        self.text = text
        self.line_starts = [0]
        for line in text.splitlines(keepends=True):
            self.line_starts.append(self.line_starts[-1] + len(line))

    def offset(self, line: int, col: int) -> int:
        return self.line_starts[line - 1] + col

    def line_col(self, offset: int) -> tuple[int, int]:
        line_idx = bisect.bisect_right(self.line_starts, offset) - 1
        return line_idx + 1, offset - self.line_starts[line_idx]

    def span_text(self, node: ast.AST) -> str:
        return self.text[self.offset(node.lineno, node.col_offset) : self.offset(node.end_lineno, node.end_col_offset)]


def in_range(node: ast.AST, ranges: list[tuple[int, int]]) -> bool:
    lineno = getattr(node, "lineno", None)
    if lineno is None:
        return False
    end_lineno = getattr(node, "end_lineno", lineno)
    return any(start <= lineno and end_lineno <= end for start, end in ranges)


def locate_operator_span(smap: SourceMap, left: ast.AST, right: ast.AST, symbol: str) -> tuple[int, int] | None:
    """ast's operator/cmpop nodes (Add, Lt, ...) carry no position of their own
    (confirmed: ast.parse('a+b').body[0].value.op.lineno is None on this Python).
    The operator token has to live somewhere in the gap between the left operand's
    end and the right operand's start, so find it there instead. Returns None
    (candidate skipped) if the exact symbol cannot be found in that gap, rather
    than guessing a position and risking a corrupt splice."""
    gap_start = smap.offset(left.end_lineno, left.end_col_offset)
    gap_end = smap.offset(right.lineno, right.col_offset)
    gap = smap.text[gap_start:gap_end]
    idx = gap.find(symbol)
    if idx == -1:
        return None
    return gap_start + idx, gap_start + idx + len(symbol)


def read_source(path: Path) -> str:
    """The ONE place source text is decoded, used for both candidate generation
    (offset computation) and mutation application (splicing), so the two can
    never disagree. Path.read_text() would silently do universal-newline
    translation (CRLF -> LF) while Path.read_bytes().decode() would not; this
    codebase's files are CRLF (confirmed: 207 \\r\\n in consumer.py alone), so
    using read_text() for offsets and read_bytes().decode() for splicing (an
    earlier version of this function did exactly that, one call for
    candidate generation, a separate one for the mutation loop) would compute
    every offset against a string 1 character shorter per preceding line than
    the string actually spliced against -- correct on line 1, increasingly
    wrong on every later line. This surfaced as mutations at consumer.py:130
    (deep in a CRLF file) being spliced at the wrong offset and landing on
    inert text, reported as false survivors even after full-suite
    confirmation. Fixed by decoding raw bytes exactly once, one way, reused
    everywhere a given file's text is needed."""
    return path.read_bytes().decode("utf-8")


def build_parents(tree: ast.AST) -> dict[ast.AST, ast.AST]:
    parents: dict[ast.AST, ast.AST] = {}
    for node in ast.walk(tree):
        for child in ast.iter_child_nodes(node):
            parents[child] = node
    return parents


# ---------------------------------------------------------------------------
# Mutation candidates
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class MutationCandidate:
    file: str
    line: int
    col: int
    kind: str
    detail: str
    original: str
    replacement: str
    start_offset: int
    end_offset: int

    def sort_key(self):
        return (self.file, self.line, self.col, self.kind, self.detail)

    def mutant_id(self) -> str:
        return f"{self.file}:{self.line}:{self.col}:{self.kind}:{self.detail}"

    def apply(self, source_text: str) -> str:
        return source_text[: self.start_offset] + self.replacement + source_text[self.end_offset :]


_ARITH_SYMBOL = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/", ast.FloorDiv: "//", ast.Mod: "%"}
# One deterministic swap target per operator (not every possible pairing), so the
# catalog stays enumerable: each instance produces exactly one arithmetic mutant.
_ARITH_SWAP = {ast.Add: "-", ast.Sub: "+", ast.Mult: "/", ast.Div: "*", ast.FloorDiv: "%", ast.Mod: "//"}

_CMP_SYMBOL = {ast.Lt: "<", ast.LtE: "<=", ast.Gt: ">", ast.GtE: ">=", ast.Eq: "==", ast.NotEq: "!="}
_CMP_SWAP = {ast.Lt: ">=", ast.LtE: ">", ast.Gt: "<=", ast.GtE: "<", ast.Eq: "!=", ast.NotEq: "=="}

# Defect fix (post-hoc adversarial review of the 200-mutant campaign): the original
# gen_arith_op_swaps only ever walked ast.BinOp, and gen_boundary_shifts' parent
# check only recognized ast.Subscript / ast.Compare / ast.Call / a Div-family
# ast.BinOp as the parent of an int literal. ast.AugAssign (`x += y`) was never
# visited by either, so every augmented assignment in the surface -- every
# accumulator, e.g. capacity.py's total_charge_eur, consumer.py's
# total_deferred_kwh, model.py's broker_contributions_kwh[...] += ... (the exact
# line the Phase 19 surviving mutant A lived on) -- got ZERO candidates, silently,
# in the original 200-mutant campaign. These two symbol maps and the two
# gen_augassign_* generators below give AugAssign the same two mutation kinds
# BinOp/Compare already had; they are deliberately NOT folded into
# gen_arith_op_swaps/gen_boundary_shifts or generate_candidates, so the original
# 200 mutants' identity and selection (already run, already reported) are not
# altered or renumbered by this fix. They are used only by generate_augassign_candidates,
# which only the --augassign-only supplement run below calls.
_AUGASSIGN_SYMBOL = {ast.Add: "+=", ast.Sub: "-=", ast.Mult: "*=", ast.Div: "/=", ast.FloorDiv: "//=", ast.Mod: "%="}
_AUGASSIGN_SWAP = {ast.Add: "-=", ast.Sub: "+=", ast.Mult: "/=", ast.Div: "*=", ast.FloorDiv: "%=", ast.Mod: "//="}


def gen_arith_op_swaps(tree: ast.AST, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.BinOp) and type(node.op) in _ARITH_SWAP and in_range(node, ranges)):
            continue
        symbol = _ARITH_SYMBOL[type(node.op)]
        span = locate_operator_span(smap, node.left, node.right, symbol)
        if span is None:
            continue
        start, end = span
        new_symbol = _ARITH_SWAP[type(node.op)]
        line, col = smap.line_col(start)
        out.append(
            MutationCandidate(
                relpath, line, col, "arith_op_swap", f"{symbol!r} -> {new_symbol!r}", symbol, new_symbol, start, end
            )
        )
    return out


def gen_cmp_op_swaps(tree: ast.AST, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Compare) and len(node.ops) == 1 and in_range(node, ranges)):
            continue
        op_type = type(node.ops[0])
        if op_type not in _CMP_SWAP:
            continue
        symbol = _CMP_SYMBOL[op_type]
        span = locate_operator_span(smap, node.left, node.comparators[0], symbol)
        if span is None:
            continue
        start, end = span
        new_symbol = _CMP_SWAP[op_type]
        line, col = smap.line_col(start)
        out.append(
            MutationCandidate(
                relpath, line, col, "cmp_op_swap", f"{symbol!r} -> {new_symbol!r}", symbol, new_symbol, start, end
            )
        )
    return out


def gen_boundary_shifts(tree: ast.AST, parents, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    out = []
    for node in ast.walk(tree):
        # bool is an int subclass; type(...) is int (not isinstance) excludes True/False.
        if not (isinstance(node, ast.Constant) and type(node.value) is int and in_range(node, ranges)):
            continue
        parent = parents.get(node)
        is_index = isinstance(parent, ast.Subscript)
        is_count = isinstance(parent, (ast.Compare, ast.Call))
        is_divisor = isinstance(parent, ast.BinOp) and isinstance(parent.op, (ast.Div, ast.FloorDiv, ast.Mod))
        if not (is_index or is_count or is_divisor):
            continue
        start = smap.offset(node.lineno, node.col_offset)
        end = smap.offset(node.end_lineno, node.end_col_offset)
        orig_text = smap.text[start:end]
        line, col = smap.line_col(start)
        for delta in (-1, 1):
            new_text = str(node.value + delta)
            if new_text == orig_text:
                continue
            out.append(
                MutationCandidate(
                    relpath, line, col, "boundary_shift", f"{orig_text} -> {new_text}", orig_text, new_text, start, end
                )
            )
    return out


def gen_augassign_arith_op_swaps(tree: ast.AST, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    """arith_op_swap for ast.AugAssign (`x += y` -> `x -= y`, etc.), the AugAssign
    half of the Defect 1 fix. AugAssign's op, like BinOp's, carries no position of
    its own, so the operator token is located the same way: it lives in the gap
    between the target's end and the value's start."""
    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.AugAssign) and type(node.op) in _AUGASSIGN_SWAP and in_range(node, ranges)):
            continue
        symbol = _AUGASSIGN_SYMBOL[type(node.op)]
        span = locate_operator_span(smap, node.target, node.value, symbol)
        if span is None:
            continue
        start, end = span
        new_symbol = _AUGASSIGN_SWAP[type(node.op)]
        line, col = smap.line_col(start)
        out.append(
            MutationCandidate(
                relpath, line, col, "arith_op_swap", f"{symbol!r} -> {new_symbol!r} (augmented assignment)",
                symbol, new_symbol, start, end,
            )
        )
    return out


def gen_augassign_boundary_shifts(tree: ast.AST, parents, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    """boundary_shift for an int literal that is directly the right-hand side of an
    ast.AugAssign (e.g. `self.hours_observed += 1`), the other half of the
    Defect 1 fix. Deliberately narrow (the literal must BE parent.value, not
    merely nested somewhere inside it): a literal nested in a larger expression on
    the right-hand side is still reachable through the existing Compare/Call/Div
    parent checks in gen_boundary_shifts wherever those already apply, so this
    only needs to cover the case those checks structurally cannot: the AugAssign
    node itself, which is not a Subscript, Compare, Call, or Div-family BinOp."""
    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Constant) and type(node.value) is int and in_range(node, ranges)):
            continue
        parent = parents.get(node)
        if not (isinstance(parent, ast.AugAssign) and parent.value is node):
            continue
        start = smap.offset(node.lineno, node.col_offset)
        end = smap.offset(node.end_lineno, node.end_col_offset)
        orig_text = smap.text[start:end]
        line, col = smap.line_col(start)
        for delta in (-1, 1):
            new_text = str(node.value + delta)
            if new_text == orig_text:
                continue
            out.append(
                MutationCandidate(
                    relpath, line, col, "boundary_shift", f"{orig_text} -> {new_text} (augmented assignment)",
                    orig_text, new_text, start, end,
                )
            )
    return out


def gen_bool_gates(tree: ast.AST, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    out = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.If, ast.While)):
            continue
        test = node.test
        if not in_range(test, ranges):
            continue
        start = smap.offset(test.lineno, test.col_offset)
        end = smap.offset(test.end_lineno, test.end_col_offset)
        orig_text = smap.text[start:end]
        line, col = smap.line_col(start)
        for replacement in ("True", "False"):
            if orig_text.strip() == replacement:
                continue
            out.append(
                MutationCandidate(
                    relpath, line, col, "bool_gate", f"condition -> {replacement}", orig_text, replacement, start, end
                )
            )
    return out


def gen_bound_removal_and_sign_flip(tree: ast.AST, smap: SourceMap, ranges, relpath: str) -> list[MutationCandidate]:
    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and not node.keywords and in_range(node, ranges)):
            continue
        is_maxmin = isinstance(node.func, ast.Name) and node.func.id in ("max", "min") and len(node.args) == 2
        is_clip = isinstance(node.func, ast.Attribute) and node.func.attr == "clip" and len(node.args) == 3
        if not (is_maxmin or is_clip):
            continue
        start = smap.offset(node.lineno, node.col_offset)
        end = smap.offset(node.end_lineno, node.end_col_offset)
        call_text = smap.text[start:end]
        line, col = smap.line_col(start)

        if is_maxmin:
            func_name = node.func.id
            for i, arg in enumerate(node.args):
                a_start = smap.offset(arg.lineno, arg.col_offset)
                a_end = smap.offset(arg.end_lineno, arg.end_col_offset)
                arg_text = smap.text[a_start:a_end]
                if arg_text == call_text:
                    continue
                out.append(
                    MutationCandidate(
                        relpath,
                        line,
                        col,
                        "bound_removal",
                        f"drop {func_name}(...) wrapper, keep operand {i}",
                        call_text,
                        arg_text,
                        start,
                        end,
                    )
                )
        else:
            arg = node.args[0]
            a_start = smap.offset(arg.lineno, arg.col_offset)
            a_end = smap.offset(arg.end_lineno, arg.end_col_offset)
            arg_text = smap.text[a_start:a_end]
            out.append(
                MutationCandidate(
                    relpath, line, col, "bound_removal", "drop clip(...) wrapper, keep value", call_text, arg_text, start, end
                )
            )

        negated = f"-({call_text})"
        out.append(
            MutationCandidate(
                relpath, line, col, "sign_flip", "negate clipped/bounded quantity", call_text, negated, start, end
            )
        )
    return out


# Swapping the two operands of one of these is a no-op in IEEE 754 (true for +
# and * of any two floats, including nan/inf operands, as far as the returned
# value goes): review finding, not a hypothesis. Swapping operands of a - b,
# a / b, a // b or a % b is NOT a no-op, so those stay eligible.
_COMMUTATIVE_BINOPS = (ast.Add, ast.Mult)


def gen_identifier_swaps(tree: ast.AST, smap: SourceMap, ranges, relpath: str) -> tuple[list[MutationCandidate], int]:
    """'Same-typed' is approximated as 'both operands are bare ast.Name nodes with
    different identifiers': this codebase carries no pervasive static type info to
    check real types against, and a bare-name pair is the case where a swap is both
    syntactically trivial (no wrapping needed) and semantically the classic
    copy-paste-swap bug this catalog item exists to catch.

    Returns (candidates, num_skipped_as_commutative): the second count is only
    incremented for a BinOp that would otherwise have produced a candidate (both
    operands bare, distinct Names) and is a + or a *, so it reflects mutations
    actually prevented, not every commutative BinOp in the file (most have a
    non-Name operand, e.g. a nested sub-expression, and were never candidates)."""
    out = []
    skipped_commutative = 0

    def try_swap(a: ast.AST, b: ast.AST, pos_node: ast.AST, where: str) -> MutationCandidate | None:
        if not (isinstance(a, ast.Name) and isinstance(b, ast.Name)) or a.id == b.id:
            return None
        a_start, a_end = smap.offset(a.lineno, a.col_offset), smap.offset(a.end_lineno, a.end_col_offset)
        b_start, b_end = smap.offset(b.lineno, b.col_offset), smap.offset(b.end_lineno, b.end_col_offset)
        if a_end > b_start:
            return None  # a should lexically precede b; skip anything unexpected rather than risk a bad splice
        pos_start = smap.offset(pos_node.lineno, pos_node.col_offset)
        pos_end = smap.offset(pos_node.end_lineno, pos_node.end_col_offset)
        orig = smap.text[pos_start:pos_end]
        new_text = smap.text[pos_start:a_start] + b.id + smap.text[a_end:b_start] + a.id + smap.text[b_end:pos_end]
        line, col = smap.line_col(pos_start)
        return MutationCandidate(
            relpath, line, col, "identifier_swap", f"swap {a.id!r} <-> {b.id!r} in {where}", orig, new_text, pos_start, pos_end
        )

    for node in ast.walk(tree):
        candidate = None
        if isinstance(node, ast.BinOp) and in_range(node, ranges):
            left, right = node.left, node.right
            would_qualify = isinstance(left, ast.Name) and isinstance(right, ast.Name) and left.id != right.id
            if would_qualify and isinstance(node.op, _COMMUTATIVE_BINOPS):
                skipped_commutative += 1  # a + b -> b + a, or a * b -> b * a: identical value, not a mutation
                continue
            candidate = try_swap(left, right, node, "BinOp")
        elif isinstance(node, ast.Compare) and len(node.ops) == 1 and in_range(node, ranges):
            candidate = try_swap(node.left, node.comparators[0], node, "Compare")
        elif isinstance(node, ast.Call) and len(node.args) >= 2 and in_range(node, ranges):
            candidate = try_swap(node.args[0], node.args[1], node, "Call args")
        if candidate is not None:
            out.append(candidate)
    return out, skipped_commutative


def generate_candidates(relpath: str, source_text: str, ranges: list[tuple[int, int]]) -> tuple[list[MutationCandidate], int]:
    """Returns (candidates, num_dropped_as_mechanically_equivalent).

    The per-kind generators above already refuse a few equivalences they can see
    locally (a commutative BinOp operand swap, a boundary shift that happens to
    reproduce the original text). This is a second, general-purpose net: apply
    EVERY surviving candidate to the source, re-parse the result, and compare
    ast.dump(mutated) to ast.dump(original) (default include_attributes=False,
    so this is a structural comparison, blind to line/col). An identical dump
    means the mutation is a no-op by construction, for any reason, not just the
    ones a specific generator happens to know about -- and it is silently
    dropped, because there is no argument to make about it: two ASTs that dump
    identically denote the identical computation. Anything NOT caught here that
    still turns out to be behaviorally inert is a different kind of claim (it
    requires reasoning about reachable program states, not just syntax), and is
    reported as a survivor with that argument stated, not dropped here."""
    tree = ast.parse(source_text, filename=relpath)
    original_dump = ast.dump(tree)
    smap = SourceMap(source_text)
    parents = build_parents(tree)

    identifier_swap_candidates, skipped_commutative = gen_identifier_swaps(tree, smap, ranges, relpath)

    candidates: list[MutationCandidate] = []
    candidates += gen_arith_op_swaps(tree, smap, ranges, relpath)
    candidates += gen_cmp_op_swaps(tree, smap, ranges, relpath)
    candidates += gen_boundary_shifts(tree, parents, smap, ranges, relpath)
    candidates += gen_bool_gates(tree, smap, ranges, relpath)
    candidates += gen_bound_removal_and_sign_flip(tree, smap, ranges, relpath)
    candidates += identifier_swap_candidates

    seen: set[tuple[int, int, str]] = set()
    unique = []
    for c in candidates:
        key = (c.start_offset, c.end_offset, c.replacement)
        if key in seen:
            continue
        seen.add(key)
        unique.append(c)
    unique.sort(key=lambda c: c.sort_key())

    kept = []
    dropped_equivalent = skipped_commutative
    for c in unique:
        mutated_dump = ast.dump(ast.parse(c.apply(source_text), filename=relpath))
        if mutated_dump == original_dump:
            dropped_equivalent += 1
            continue
        kept.append(c)
    return kept, dropped_equivalent


def generate_augassign_candidates(relpath: str, source_text: str, ranges: list[tuple[int, int]]) -> tuple[list[MutationCandidate], int]:
    """Defect 1 fix: a separate entry point covering ONLY ast.AugAssign, the node
    type generate_candidates never visited (see the _AUGASSIGN_SYMBOL comment
    above). Kept separate from generate_candidates, rather than folded into it, so
    the original 200-mutant campaign's candidate pool -- already generated,
    already selected, already run and reported -- is not changed or renumbered by
    this fix; this function is called only by the --augassign-only supplement.
    Same equivalence guard as generate_candidates (ast.dump comparison, blind to
    line/col), applied to exactly the same source text and ranges."""
    tree = ast.parse(source_text, filename=relpath)
    original_dump = ast.dump(tree)
    smap = SourceMap(source_text)
    parents = build_parents(tree)

    candidates: list[MutationCandidate] = []
    candidates += gen_augassign_arith_op_swaps(tree, smap, ranges, relpath)
    candidates += gen_augassign_boundary_shifts(tree, parents, smap, ranges, relpath)

    seen: set[tuple[int, int, str]] = set()
    unique = []
    for c in candidates:
        key = (c.start_offset, c.end_offset, c.replacement)
        if key in seen:
            continue
        seen.add(key)
        unique.append(c)
    unique.sort(key=lambda c: c.sort_key())

    kept = []
    dropped_equivalent = 0
    for c in unique:
        mutated_dump = ast.dump(ast.parse(c.apply(source_text), filename=relpath))
        if mutated_dump == original_dump:
            dropped_equivalent += 1
            continue
        kept.append(c)
    return kept, dropped_equivalent


# ---------------------------------------------------------------------------
# Budget allocation
# ---------------------------------------------------------------------------


def allocate_budget(budget: int, weights: dict[str, int], availability: dict[str, int]) -> dict[str, int]:
    """Proportional, largest-remainder allocation, water-filled against each file's
    actual candidate count.

    A flat proportional split (e.g. metrics.py gets exactly 60/200 of the budget)
    is not enough on its own: metrics.py's surface only contains 40 candidate
    mutations at all (it is a small, four-branch file), so a flat 60-mutant quota
    would silently under-spend the budget by 20 mutants rather than actually
    running 200. Instead: compute the proportional split among files still under
    their cap, place it, cap any file that overflowed its own availability at
    that availability, remove it from consideration, and repeat the proportional
    split of whatever overflowed among the files still with headroom -- standard
    water-filling. Every step uses the same largest-remainder tie-break (by
    fractional part, ties broken by the fixed WEIGHTS order) as a flat split
    would, so the whole procedure is deterministic for a given (budget, weights,
    availability) and terminates in at most len(weights) rounds (each round either
    finishes, or removes at least one file from consideration for good)."""
    order = list(weights.keys())
    quotas = {f: 0 for f in order}
    active = set(order)
    to_place = min(budget, sum(availability.values()))

    while to_place > 0 and active:
        weight_total = sum(weights[f] for f in active)
        raw = {f: to_place * weights[f] / weight_total for f in active}
        floors = {f: int(raw[f]) for f in active}
        remainder = to_place - sum(floors.values())
        by_fraction = sorted(active, key=lambda f: (-(raw[f] - floors[f]), order.index(f)))
        for f in by_fraction[: max(remainder, 0)]:
            floors[f] += 1

        overflow = 0
        newly_capped = []
        for f in active:
            proposed = quotas[f] + floors[f]
            cap = availability[f]
            if proposed > cap:
                overflow += proposed - cap
                quotas[f] = cap
                newly_capped.append(f)
            else:
                quotas[f] = proposed
        for f in newly_capped:
            active.discard(f)
        to_place = overflow

    return quotas


def select_mutants(candidates_by_file: dict[str, list[MutationCandidate]], quotas: dict[str, int], seed: int):
    """Deterministic selection: exact pool if it fits the quota, else a fixed-seed
    random.Random(seed).sample() of the already-sorted pool, re-sorted afterward.
    A fresh Random(seed) is used per file so a given file's sample never depends on
    which other files were processed first."""
    selected: list[MutationCandidate] = []
    capped: list[str] = []
    for relpath, quota in quotas.items():
        pool = candidates_by_file.get(relpath, [])
        effective_quota = min(quota, len(pool))
        if effective_quota < quota:
            capped.append(relpath)
        if len(pool) <= effective_quota:
            chosen = list(pool)
        else:
            chosen = random.Random(seed).sample(pool, effective_quota)
            chosen.sort(key=lambda c: c.sort_key())
        selected.extend(chosen)
    selected.sort(key=lambda c: c.sort_key())
    return selected, capped


# ---------------------------------------------------------------------------
# Real-tree integrity: hash manifest of src/ and scripts/
# ---------------------------------------------------------------------------


def collect_guarded_files(repo_root: Path) -> list[Path]:
    files = []
    for base in ("src", "scripts"):
        for p in sorted((repo_root / base).rglob("*")):
            if p.is_file() and "__pycache__" not in p.parts:
                files.append(p)
    return files


def compute_manifest(paths: list[Path]) -> dict[str, str]:
    return {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}


def manifest_digest(manifest: dict[str, str]) -> str:
    combined = "\n".join(f"{k}:{v}" for k, v in sorted(manifest.items()))
    return hashlib.sha256(combined.encode()).hexdigest()


def verify_manifest_or_abort(before: dict[str, str], after: dict[str, str]) -> None:
    if before == after:
        return
    changed = sorted(set(before) ^ set(after)) or [k for k in before if before[k] != after.get(k)]
    raise SystemExit(
        "ABORT: real src/ or scripts/ changed during the mutation run. "
        f"Affected paths: {changed}. This must never happen; the mutation loop only "
        "ever writes inside the scratch tree. Investigate before trusting any other "
        "output of this run."
    )


# ---------------------------------------------------------------------------
# Scratch tree
# ---------------------------------------------------------------------------


def prepare_scratch_tree(repo_root: Path, scratch_root: Path) -> Path:
    if scratch_root.exists():
        shutil.rmtree(scratch_root)

    def ignore(_dir, names):
        return [n for n in names if n in EXCLUDE_DIR_NAMES]

    shutil.copytree(repo_root, scratch_root, ignore=ignore)
    return scratch_root


def run_pytest(cwd: Path, pytest_args: list[str], timeout_s: int) -> tuple[bool, str]:
    """Returns (all_passed, tail_of_output). A non-zero return code from pytest, or
    a timeout, both count as 'a test failed / detected something wrong' (a mutant
    that hangs a test has still been caught, just by a different symptom)."""
    cmd = [sys.executable, "-m", "pytest", "-p", "no:cacheprovider", *pytest_args]
    try:
        proc = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, timeout=timeout_s)
        return proc.returncode == 0, (proc.stdout[-2000:] + proc.stderr[-500:])
    except subprocess.TimeoutExpired:
        return False, f"TIMEOUT after {timeout_s}s"


def targeted_pytest_args(relpath: str) -> list[str]:
    # No -n here, deliberately, for every file including capacity.py: xdist worker
    # startup (several seconds to spin up N workers) dominates a single targeted
    # module subset, and -x means a KILLED mutant (the common case) stops at the
    # first failing test anyway, so there is nothing to parallelize against for
    # most mutants. -n only pays for itself on the FULL suite confirmation step
    # (FULL_SUITE_ARGS below), which always runs to completion since it is only
    # invoked for mutants that already survived the fast targeted pass.
    return ["-q", "--no-header", "-x", *TARGETED_TESTS[relpath]]


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class MutantResult:
    candidate: MutationCandidate
    killed_targeted: bool
    targeted_note: str
    confirmed_survivor: bool | None = None  # None until/unless it needed full-suite confirmation


def append_jsonl(path: Path, record: dict) -> None:
    """Crash-safety net: a full run takes tens of minutes and a run that gets
    interrupted (killed process, machine sleep, anything short of a clean exit)
    would otherwise lose every result computed so far, because write_report()
    only runs at the very end. Every verdict is appended here as one JSON line,
    opened/written/flushed/closed each time rather than held open, specifically
    so a hard kill loses at most the one in-flight mutant, not the whole run."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")
        f.flush()


def write_report(
    path: Path,
    args: argparse.Namespace,
    weights: dict[str, int],
    quotas: dict[str, int],
    candidates_by_file: dict[str, list[MutationCandidate]],
    capped_files: list[str],
    results: list[MutantResult],
    runtime_s: float,
    manifest_ok: bool,
    dropped_equivalent_total: int = 0,
) -> None:
    lines: list[str] = []
    lines.append("# Phase 20.3 mutation testing report")
    lines.append("")
    lines.append(
        "Generated by `scripts/mutation_check.py` (committed harness; see that file for the full "
        "design rationale in its module docstring and inline comments). This section is written "
        "by the harness itself and is purely factual: mutant generation, targeted-subset result, "
        "full-suite confirmation. Triage (which class each survivor falls into, and what was done "
        "about it) is a separate, hand-authored section appended below the harness output."
    )
    lines.append("")

    lines.append("## Mutation catalog")
    lines.append("")
    for kind, desc in CATALOG:
        lines.append(f"- `{kind}`: {desc}")
    lines.append("")

    lines.append("## Surface and allocation")
    lines.append("")
    lines.append(f"Budget: {args.budget}. Seed: {args.seed}.")
    lines.append("")
    lines.append("| file | surface line ranges | candidates in surface | quota | capped |")
    lines.append("|---|---|---|---|---|")
    for relpath in weights:
        ranges = TARGETS[relpath]
        range_str = ", ".join(f"{s}-{e}" for s, e in ranges) if ranges != [(1, 10**6)] else "whole file"
        n_candidates = len(candidates_by_file.get(relpath, []))
        lines.append(f"| `{relpath}` | {range_str} | {n_candidates} | {quotas[relpath]} | {'yes' if relpath in capped_files else 'no'} |")
    lines.append("")

    lines.append("## Per-file results")
    lines.append("")
    lines.append("| file | generated | killed (targeted) | survived targeted | confirmed survivors (full suite) |")
    lines.append("|---|---|---|---|---|")
    by_file: dict[str, list[MutantResult]] = {}
    for r in results:
        by_file.setdefault(r.candidate.file, []).append(r)
    total_gen = total_killed = total_survived_targeted = total_confirmed = 0
    for relpath in weights:
        rs = by_file.get(relpath, [])
        gen = len(rs)
        killed = sum(1 for r in rs if r.killed_targeted)
        survived = gen - killed
        confirmed = sum(1 for r in rs if r.confirmed_survivor)
        total_gen += gen
        total_killed += killed
        total_survived_targeted += survived
        total_confirmed += confirmed
        lines.append(f"| `{relpath}` | {gen} | {killed} | {survived} | {confirmed} |")
    lines.append(f"| **total** | **{total_gen}** | **{total_killed}** | **{total_survived_targeted}** | **{total_confirmed}** |")
    lines.append("")

    lines.append("## Confirmed survivors (harness output; triage appended below)")
    lines.append("")
    confirmed = [r for r in results if r.confirmed_survivor]
    if not confirmed:
        lines.append("None.")
    else:
        lines.append("| file:line | kind | mutation (original -> replacement) | note |")
        lines.append("|---|---|---|---|")
        for r in sorted(confirmed, key=lambda r: r.candidate.sort_key()):
            c = r.candidate
            orig = c.original.replace("|", "\\|").replace("\n", " ")
            repl = c.replacement.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| `{c.file}:{c.line}` | {c.kind} | `{orig}` -> `{repl}` | {c.detail} |")
    lines.append("")

    lines.append("## Run metadata")
    lines.append("")
    lines.append(f"- Harness runtime: {runtime_s:.1f}s")
    lines.append(f"- Real src/ and scripts/ sha256 manifest unchanged start-to-end: {'yes' if manifest_ok else 'NO -- SEE ABORT'}")
    lines.append(
        f"- Mechanically-equivalent mutants dropped before selection: {dropped_equivalent_total}. Rule: (1) a "
        "commutative BinOp (ast.Add or ast.Mult) is never offered to identifier_swap, since swapping its two "
        "operands changes nothing in IEEE 754, for any float operands including nan/inf; (2) after generation, "
        "any candidate whose ast.dump(mutated) equals ast.dump(original) (structural comparison, blind to "
        "line/col) is dropped, for any reason, not just rule (1)'s. Mutations that are equivalent for a reason "
        "that requires reasoning about reachable program state rather than pure syntax are NOT dropped here; "
        "they are generated, run, and (if they survive) reported as survivors with the argument stated, in the "
        "triage section, so a reader can disagree with the argument."
    )
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--budget", type=int, default=200, help="total mutants to run (default 200)")
    parser.add_argument("--files", nargs="*", default=None, help="substrings to restrict target files (default: all)")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help=f"fixed sampling seed (default {DEFAULT_SEED})")
    parser.add_argument(
        "--report", type=Path, default=REPO_ROOT / "docs" / "verification" / "mutation_report.md", help="output report path"
    )
    parser.add_argument(
        "--augassign-only",
        action="store_true",
        help=(
            "Defect 1 fix's supplement path: generate candidates ONLY from ast.AugAssign nodes "
            "(generate_augassign_candidates), instead of the normal full pool (generate_candidates). "
            "Does not touch or re-select the original 200-mutant campaign's candidate pool; use this "
            "for a separate supplementary run covering the AugAssign gap that pool never saw."
        ),
    )
    parser.add_argument(
        "--offset",
        type=int,
        default=0,
        help=(
            "skip this many entries of the deterministic (budget, seed, files) mutant list before processing "
            "the rest; lets one long run be split into foreground chunks that finish inside a tool timeout. "
            "Chunk N+1's offset is chunk N's offset plus however many mutants chunk N actually processed "
            "(readable from chunk N's .jsonl progress log if it did not finish); the chunks' reports "
            "recombine by hand into one docs/verification/mutation_report.md, since each chunk only ever "
            "sees and reports on its own slice."
        ),
    )
    args = parser.parse_args(argv)

    t0 = time.time()
    progress_path = args.report.with_suffix(".jsonl")
    if progress_path.exists():
        progress_path.unlink()  # each run starts a fresh crash-safety log; stale lines would misreport a new run

    guarded_files = collect_guarded_files(REPO_ROOT)
    manifest_before = compute_manifest(guarded_files)
    print(f"[manifest] hashed {len(guarded_files)} files under src/ and scripts/ (real tree). digest={manifest_digest(manifest_before)[:16]}")

    weights = dict(WEIGHTS)
    if args.files:
        needles = [f.lower() for f in args.files]
        weights = {k: v for k, v in WEIGHTS.items() if any(n in k.lower() for n in needles)}
    if not weights:
        print("no targets matched --files", file=sys.stderr)
        return 1

    # Defect 2 fix (post-hoc adversarial review): everything from here down touches
    # the scratch tree, and the post-run manifest check (below, in `finally`) is
    # the one thing that would catch the real src/scripts/ having been corrupted
    # if any of it crashes. The check used to run only after this whole block
    # returned normally -- the happy path, exactly the path that does NOT need it.
    # Wrapping the block in try/finally means a mid-run crash (an unexpected
    # exception from pytest invocation, candidate generation, anything) still
    # always runs the manifest comparison before that crash is allowed to
    # propagate, instead of skipping straight past it.
    candidates_by_file: dict[str, list[MutationCandidate]] = {}
    quotas: dict[str, int] = {}
    capped_files: list[str] = []
    dropped_equivalent_total = 0
    results: list[MutantResult] = []
    manifest_ok = False
    try:
        scratch_root = prepare_scratch_tree(REPO_ROOT, SCRATCH_ROOT)
        print(f"[scratch] clean copy prepared at {scratch_root}")

        generator = generate_augassign_candidates if args.augassign_only else generate_candidates
        for relpath in weights:
            source_text = read_source(scratch_root / relpath)
            kept, dropped = generator(relpath, source_text, TARGETS[relpath])
            candidates_by_file[relpath] = kept
            dropped_equivalent_total += dropped
            print(f"[generate] {relpath}: {len(kept)} candidate mutations ({dropped} dropped as mechanically equivalent)")

        availability = {relpath: len(candidates_by_file[relpath]) for relpath in weights}
        quotas = allocate_budget(args.budget, weights, availability)
        selected, capped_files = select_mutants(candidates_by_file, quotas, args.seed)
        print(f"[select] {len(selected)} mutants selected for budget {args.budget} (seed {args.seed}); "
              f"{dropped_equivalent_total} dropped as mechanically equivalent before selection")
        if capped_files:
            print(f"[select] quota exceeded available candidates for: {capped_files} (took all available)")
        if args.offset:
            skipped = selected[: args.offset]
            selected = selected[args.offset :]
            print(f"[offset] skipping first {len(skipped)} of the deterministic list; processing {len(selected)} remaining")

        for relpath in weights:
            muts = [c for c in selected if c.file == relpath]
            if not muts:
                continue
            target_path = scratch_root / relpath
            original_bytes = target_path.read_bytes()
            original_text = read_source(target_path)
            pytest_args = targeted_pytest_args(relpath)
            for c in muts:
                mutated_text = c.apply(original_text)
                target_path.write_bytes(mutated_text.encode("utf-8"))
                try:
                    passed, _ = run_pytest(scratch_root, pytest_args, TARGETED_TIMEOUT_S)
                finally:
                    target_path.write_bytes(original_bytes)  # restore inside the SCRATCH tree, always
                killed = not passed
                results.append(MutantResult(c, killed, "targeted subset failed" if killed else "targeted subset passed"))
                print(f"[{'killed' if killed else 'SURVIVED'}] {c.file}:{c.line} {c.kind}: {c.detail}", flush=True)
                append_jsonl(progress_path, {"stage": "targeted", "id": c.mutant_id(), "file": c.file, "line": c.line,
                                              "col": c.col, "kind": c.kind, "detail": c.detail, "killed": killed})

        survivors = [r for r in results if not r.killed_targeted]
        print(f"[confirm] {len(survivors)} targeted-subset survivor(s); re-running each against the full suite")
        for r in survivors:
            c = r.candidate
            target_path = scratch_root / c.file
            original_bytes = target_path.read_bytes()
            original_text = read_source(target_path)
            mutated_text = c.apply(original_text)
            target_path.write_bytes(mutated_text.encode("utf-8"))
            try:
                passed, _ = run_pytest(scratch_root, FULL_SUITE_ARGS, FULL_SUITE_TIMEOUT_S)
            finally:
                target_path.write_bytes(original_bytes)
            r.confirmed_survivor = passed  # still passes the full suite => genuinely survives
            print(
                f"[{'CONFIRMED SURVIVOR' if r.confirmed_survivor else 'killed by full suite'}] {c.file}:{c.line} {c.kind}: {c.detail}",
                flush=True,
            )
            append_jsonl(progress_path, {"stage": "confirm", "id": c.mutant_id(), "file": c.file, "line": c.line,
                                          "col": c.col, "kind": c.kind, "detail": c.detail, "confirmed_survivor": r.confirmed_survivor})
    finally:
        manifest_after = compute_manifest(guarded_files)
        manifest_ok = manifest_before == manifest_after
        print(f"[manifest] real src/scripts unchanged at exit: {manifest_ok}. digest={manifest_digest(manifest_after)[:16]}")
        verify_manifest_or_abort(manifest_before, manifest_after)

    runtime_s = time.time() - t0
    write_report(
        args.report, args, weights, quotas, candidates_by_file, capped_files, results, runtime_s, manifest_ok,
        dropped_equivalent_total,
    )
    print(f"[done] runtime {runtime_s:.1f}s. report written to {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
